(function(){
  const app=document.querySelector('.app');
  const hero=app.querySelector('.studentHeader');
  const statsPanel=app.querySelector('.stats');
  const subjectNav=document.getElementById('nav');
  const learningGrid=app.querySelector('.grid');
  const sourceLibrary=app.querySelector('.sources');
  const expandedSubjects={};
  let uiMode='HOME';

  const modeNav=document.createElement('nav');
  modeNav.id='modeNav';modeNav.className='modeNav';modeNav.setAttribute('aria-label','Learning modes');
  const views={};
  const makeView=(name)=>{const el=document.createElement('section');el.id=name.toLowerCase()+'View';el.className='modeView hidden';views[name]=el;return el};
  ['HOME','LEARN','PRACTICE','REVIEW','WRITING','PARENT'].forEach(makeView);
  views.LEARN.append(subjectNav,learningGrid);
  views.PARENT.append(statsPanel,sourceLibrary);
  app.replaceChildren(hero,modeNav,...Object.values(views));

  const modeLabels={HOME:'🏠 Ry’s Home',LEARN:'📚 Learn',PRACTICE:'🎯 Practice',REVIEW:'🔁 Review',WRITING:'✍️ Writing',PARENT:'🔒 Parent Tools'};
  function renderModeNav(){modeNav.innerHTML='';Object.entries(modeLabels).forEach(([key,label])=>{const b=document.createElement('button');b.textContent=label;b.className=key===uiMode?'active':'';b.setAttribute('aria-current',key===uiMode?'page':'false');b.onclick=()=>setMode(key);modeNav.appendChild(b)})}
  function setMode(name,scroll=true){uiMode=name;RyNarrator?.stop();Object.entries(views).forEach(([key,el])=>el.classList.toggle('hidden',key!==name));renderModeNav();if(name==='HOME')renderHome();if(name==='PRACTICE')renderPractice();if(name==='REVIEW')renderReviewHub();if(name==='WRITING')renderWritingHub();if(name==='PARENT')renderParent();if(scroll)hero.scrollIntoView({behavior:'smooth',block:'start'})}
  function findLesson(subject,matcher){const lessons=D[subject]?.lessons||[];let index=typeof matcher==='string'?lessons.findIndex(l=>l.id===matcher):lessons.findIndex(l=>matcher.test(l.title));if(index<0)index=0;return{subject,index,lesson:lessons[index]}}
  function openLesson(subject,matcher){const found=findLesson(subject,matcher);expandedSubjects[subject]=false;subj=subject;li=found.index;qi=0;save();render();setMode('LEARN');return found}
  function dueCount(){return Object.values(st.retention).filter(t=>Date.now()-new Date(t).getTime()>=86400000).length}
  function waitingCount(){return archive().filter(x=>x.status==='waiting_for_chatgpt').length}
  function weeklyItems(){return[
    {day:'1',subject:'SS',label:'Ancient Israel final retrieval + official guide',match:'ss_v21_israel_final'},
    {day:'2',subject:'ELA',label:'Unit 2 reading skills + clauses',match:'ela_v21_unit2_map'},
    {day:'3',subject:'MATH',label:'Integers, coordinates + Big 8',match:'math_v21_integers'},
    {day:'4',subject:'SCI',label:'Environments + populations',match:'science_v21_ecosystem_vocab'},
    {day:'5',subject:'SS',label:'Ancient Egypt: Nile, map + rule',match:'ss_v21_egypt_geography'}
  ].map(x=>({...x,...findLesson(x.subject,x.match)}))}
  function renderHome(){
    const week=weeklyItems(),next=week.find(x=>!st.lessonDone[x.lesson.id])||week[0];
    views.HOME.innerHTML=`<div class="startGrid"><article class="startCard"><span class="kicker">START HERE</span><h2>${esc(D[next.subject].icon+' '+D[next.subject].name)}</h2><h3>${esc(next.lesson.title)}</h3><p>One focused session. Your work saves automatically on this computer.</p><button class="primary bigStart" id="startNext">Start my next step →</button></article><article class="sessionCard"><span class="kicker">20–30 MINUTE PLAN</span><ol><li><b>3 min:</b> retrieve yesterday’s idea</li><li><b>12–15 min:</b> learn today’s priority</li><li><b>5–8 min:</b> practice one question at a time</li><li><b>2 min:</b> teach it back in your own words</li></ol></article></div><div class="statusRow"><button id="homeMissed"><b>${st.missed.length}</b><span>missed ideas to repair</span></button><button id="homeRetention"><b>${dueCount()}</b><span>retention checks due</span></button><button id="homeWriting"><b>${waitingCount()}</b><span>writing responses waiting</span></button></div><section class="weekPanel"><div class="sectionHead"><div><span class="kicker">THIS WEEK</span><h2>Five clear priorities</h2></div><p>Older lessons stay in Learn. This list shows what matters first.</p></div><div class="weekCards">${week.map(x=>`<button class="weekCard ${st.lessonDone[x.lesson.id]?'done':''}" data-subject="${x.subject}" data-id="${x.lesson.id}"><span>DAY ${x.day}</span><b>${esc(x.label)}</b><small>${st.lessonDone[x.lesson.id]?'✓ Practice cycle complete':'Open priority'}</small></button>`).join('')}</div></section>`;
    document.getElementById('startNext').onclick=()=>openLesson(next.subject,next.lesson.id);
    document.querySelectorAll('.weekCard').forEach(b=>b.onclick=()=>openLesson(b.dataset.subject,b.dataset.id));
    document.getElementById('homeMissed').onclick=()=>{setMode('LEARN');reviewMissed()};
    document.getElementById('homeRetention').onclick=()=>{setMode('LEARN');retentionReview()};
    document.getElementById('homeWriting').onclick=()=>setMode('WRITING');
  }
  function priorityIndexes(){const lessons=D[subj].lessons;if(subj==='SCI'){const order=['science_v21_ecosystem_vocab','science_v21_population_variables','science_v21_interactions','science_v21_health_invasive','science_v21_mastery',...SCIENCE_REQUIRED_ORDER];let indexes=order.map(id=>lessons.findIndex(l=>l.id===id)).filter(i=>i>=0);if(!indexes.includes(li))indexes.unshift(li);return[...new Set(indexes)].slice(0,8)}if(subj==='SS'){const guide=['ss_v21_israel_final','ss_v20_study_guide','ss_v20_migrations','ss_v20_kingdom_cyrus','ss_v20_mastery_test','ss_v21_egypt_geography','ss_v21_egypt_rule','ss_v21_egypt_nile'];let ordered=guide.map(id=>lessons.findIndex(l=>l.id===id)).filter(i=>i>=0);if(!ordered.includes(li))ordered.unshift(li);return[...new Set(ordered)].slice(0,8)}let indexes=lessons.map((l,i)=>/^(CURRENT|DO FIRST|DO SECOND|DO THIRD|DO FOURTH)/.test(l.title)?i:-1).filter(i=>i>=0);if(!indexes.length)indexes=lessons.map((_,i)=>i).slice(0,6);if(!indexes.includes(li))indexes.unshift(li);return[...new Set(indexes)].slice(0,8)}
  function lessonButton(l,i){let b=document.createElement('button');b.className='lesson '+(i===li?'active ':'')+(st.lessonDone[l.id]?'mastered':'');b.innerHTML=`<b>${i+1}. ${esc(l.title)}</b><small>${st.lessonDone[l.id]?'✓ practice cycle complete':'Teach → practice → apply'}</small>`;b.onclick=()=>{li=i;qi=0;save();renderMain();side()};return b}
  nav=function(){subjectNav.innerHTML='<div class="subjectPrompt"><b>Choose one subject</b><span>Then choose a priority lesson or browse the full library.</span></div>';Object.entries(D).forEach(([key,value])=>{let b=document.createElement('button');b.textContent=value.icon+' '+value.name;b.className=key===subj?'active':'';b.onclick=()=>{subj=key;li=0;qi=0;save();render()};subjectNav.appendChild(b)})};
  side=function(){const box=document.getElementById('side'),lessons=D[subj].lessons,showAll=!!expandedSubjects[subj];box.innerHTML=`<div class="sideHead"><span class="kicker">${showAll?'FULL LIBRARY':'PRIORITY PATH'}</span><b>${esc(D[subj].name)}</b><small>${showAll?lessons.length+' lessons available':'Up to 8 next-step lessons'}</small></div>`;if(showAll){let search=document.createElement('input');search.className='lessonSearch';search.placeholder='Search '+D[subj].name+' lessons';search.setAttribute('aria-label','Search lessons');box.appendChild(search);let list=document.createElement('div');box.appendChild(list);const draw=()=>{let term=search.value.trim().toLowerCase();list.innerHTML='';lessons.forEach((l,i)=>{if(!term||l.title.toLowerCase().includes(term))list.appendChild(lessonButton(l,i))})};search.oninput=draw;draw()}else priorityIndexes().forEach(i=>box.appendChild(lessonButton(lessons[i],i)));let toggle=document.createElement('button');toggle.className='browseAll';toggle.textContent=showAll?'← Show priority path':'Browse all '+lessons.length+' lessons';toggle.onclick=()=>{expandedSubjects[subj]=!showAll;side()};box.appendChild(toggle);setTimeout(()=>box.querySelector('.active')?.scrollIntoView({block:'nearest'}),0)};
  function testItems(currentOnly){return Object.entries(D).flatMap(([subject,value])=>value.lessons.map((lesson,index)=>({subject,lesson,index}))).filter(x=>x.lesson.test&&(!currentOnly||/(CURRENT|OFFICIAL|VOCABULARY|UNIT|PRACTICE TEST)/.test(x.lesson.title)))}
  function testCard(x){return`<button class="libraryCard" data-subject="${x.subject}" data-id="${x.lesson.id}"><span>${D[x.subject].icon} ${esc(D[x.subject].name)}</span><b>${esc(x.lesson.title)}</b><small>Independent first-attempt scoring</small></button>`}
  function bindLibraryCards(root){root.querySelectorAll('[data-subject][data-id]').forEach(b=>b.onclick=()=>openLesson(b.dataset.subject,b.dataset.id))}
  function renderPractice(){const featured=testItems(true).slice(0,8),all=testItems(false);views.PRACTICE.innerHTML=`<div class="pageIntro"><span class="kicker">PRACTICE</span><h2>Choose the kind of practice</h2><p>Practice is separate from teaching. Use Learn first when vocabulary or ideas are unfamiliar.</p></div><div class="hubCards">${featured.map(testCard).join('')}</div><details class="allLibrary"><summary>Browse all ${all.length} independent checks and prior forms</summary><div class="hubCards"><a class="hubCard" href="ela-unit1-practice.html"><span>ELA • PRIOR UNIT 1</span><b>Unit 1 guided practice forms</b><small>Preserved for cumulative retrieval</small></a>${all.map(testCard).join('')}</div></details>`;bindLibraryCards(views.PRACTICE)}
  function renderReviewHub(){views.REVIEW.innerHTML=`<div class="pageIntro"><span class="kicker">REVIEW</span><h2>Repair, then retrieve later</h2><p>First-attempt scores stay honest. Corrected work shows learning without erasing the original evidence.</p></div><div class="choiceCards"><button id="openMissed"><b>${st.missed.length}</b><span>Review missed ideas</span><small>Recall first → reveal choices → explain the repair</small></button><button id="openRetention"><b>${dueCount()}</b><span>Delayed checks due</span><small>Return after 24+ hours in a fresh format</small></button></div>`;document.getElementById('openMissed').onclick=()=>{setMode('LEARN');reviewMissed()};document.getElementById('openRetention').onclick=()=>{setMode('LEARN');retentionReview()}}
  function renderWritingHub(){let writing=D.ELA.lessons.map((lesson,index)=>({subject:'ELA',lesson,index})).filter(x=>/(Unit 2|Reading Buddies|Chimpanzees|Clauses|Narrative|Dialogue|Writing|Rubric|Ending|Constructed|Summary)/i.test(x.lesson.title)),current=writing.filter(x=>/^CURRENT OCT\. 9/.test(x.lesson.title)).slice(0,4);views.WRITING.innerHTML=`<div class="pageIntro"><span class="kicker">WRITING</span><h2>Writing World</h2><p>A distraction-reduced path for planning, evidence, summarizing, drafting, revising, and independent transfer.</p></div><div class="writingSteps"><span>1 • Decode</span><span>2 • Plan</span><span>3 • Draft</span><span>4 • Revise</span><span>5 • Submit</span></div><div class="hubCards">${current.map(testCard).join('')}</div><details class="allLibrary"><summary>Browse all ${writing.length} writing lessons</summary><div class="hubCards">${writing.map(testCard).join('')}</div></details>`;bindLibraryCards(views.WRITING)}
  function renderParent(){stats();views.PARENT.querySelectorAll('.parentPanel').forEach(x=>x.remove());let panel=document.createElement('section');panel.className='parentPanel';panel.innerHTML=`<div class="pageIntro"><span class="kicker">PARENT TOOLS</span><h2>Progress, sources, and records</h2><p>These controls are kept out of Ry’s lesson path. Progress is stored on this device.</p></div><div class="parentActions"><button id="parentExport">Export writing for ChatGPT</button><button id="parentBackup">Backup progress</button><button id="parentRestore">Restore a compatible backup</button><a href="GOVERNANCE.md">Open governance rules</a></div>`;views.PARENT.insertBefore(panel,sourceLibrary);document.getElementById('parentExport').onclick=exportWriting;document.getElementById('parentBackup').onclick=backup;document.getElementById('parentRestore').onclick=restore}
  function simplifyLessonTools(){['exportW','backup','restore'].forEach(id=>document.getElementById(id)?.classList.add('hidden'))}
  const coreRender=render;render=function(){coreRender();simplifyLessonTools();setMode('LEARN',false)};
  const coreRenderMain=renderMain;renderMain=function(){coreRenderMain();simplifyLessonTools()};
  coreRender();simplifyLessonTools();setMode('HOME',false);
  window.__RY_ORGANIZER__={setMode,openLesson,weeklyItems,priorityIndexes};
})();
